import{head,toast,modal,esc}from'./ui.js';
import{signedIn,accountEmail,register,login,logout,pushCloud,pullCloud,createMcpAccess}from'./sync.js';
export function renderAccount(root){
 if(signedIn()){
  root.innerHTML=head('Hesabım','Verilerin tüm cihazlarında güvenle eşitlensin')+`<div class="grid two-col"><div class="card"><h2>Giriş yapıldı</h2><p>${esc(accountEmail())}</p><p class="muted">Harcamalar, abonelikler, notlar, kısayollar ve ayarlar Cloudflare üzerinde senkronize edilir.</p><div class="actions"><button class="secondary" id="logout">Çıkış yap</button><button class="primary" id="sync-now">Şimdi eşitle</button></div></div><div class="card"><h2>ChatGPT bağlantısı</h2><p class="muted">ChatGPT'nin not, harcama ve aboneliklerini yönetebilmesi için kişisel MCP bağlantını oluştur. OpenAI API anahtarı veya API ücreti gerekmez.</p><div class="actions"><button class="primary" id="create-mcp">MCP bağlantısı oluştur</button></div></div></div>`;
  root.querySelector('#logout').onclick=()=>{logout();renderAccount(root);toast('Hesaptan çıkış yapıldı')};
  root.querySelector('#sync-now').onclick=async e=>{e.currentTarget.disabled=true;try{const changed=await pullCloud();if(!changed)await pushCloud();toast('Veriler eşitlendi')}catch(error){toast(error.message)}finally{renderAccount(root)}};
  root.querySelector('#create-mcp').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='Oluşturuluyor…';try{const{url}=await createMcpAccess();modal('ChatGPT MCP bağlantısı',`<p class="muted">Bu bağlantı hesabındaki verileri değiştirme yetkisi verir. Gizli tut; yeniden oluşturursan eski bağlantı iptal edilir.</p><div class="share-link-row"><input id="mcp-url" readonly value="${esc(url)}"><button class="primary" id="copy-mcp-url">Kopyala</button></div><p class="muted">ChatGPT veya Codex'te MCP sunucu adresi istenen alana bu bağlantıyı ekle.</p>`);document.querySelector('#copy-mcp-url').onclick=async()=>{await navigator.clipboard.writeText(url);toast('MCP bağlantısı kopyalandı')}}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='MCP bağlantısı oluştur'}};return;
 }
 root.innerHTML=head('Hesap','Bilgisayar ve telefonda aynı verileri kullan')+`<div class="grid two-col"><form class="card" id="login-form"><h2>Giriş yap</h2><div class="field"><label>E-posta</label><input name="email" type="email" autocomplete="email" required></div><div class="field" style="margin-top:12px"><label>Parola</label><input name="password" type="password" autocomplete="current-password" minlength="8" required></div><div class="actions"><button class="primary">Giriş yap</button></div></form><form class="card" id="register-form"><h2>İlk hesabı oluştur</h2><p class="muted">Bunu mevcut verilerinin bulunduğu bilgisayarda bir kez yap. Mevcut veriler otomatik yüklenir.</p><div class="field"><label>E-posta</label><input name="email" type="email" autocomplete="email" required></div><div class="field" style="margin-top:12px"><label>Parola (en az 8 karakter)</label><input name="password" type="password" autocomplete="new-password" minlength="8" required></div><div class="field" style="margin-top:12px"><label>Kurulum kodu</label><input name="inviteCode" required></div><div class="actions"><button class="primary">Hesabı oluştur</button></div></form></div>`;
 const run=handler=>async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),values=Object.fromEntries(new FormData(event.currentTarget));button.disabled=true;try{await handler(values);toast('Hesap bağlandı ve veriler eşitlendi');renderAccount(root)}catch(error){toast(error.message)}finally{button.disabled=false}};
 root.querySelector('#login-form').onsubmit=run(({email,password})=>login(email,password));root.querySelector('#register-form').onsubmit=run(({email,password,inviteCode})=>register(email,password,inviteCode));
}
