const DB='ado-command-center',VER=1,stores=['expenses','subscriptions','notes','shortcuts','commandHistory'];let db;
export async function initDB(){if(db)return db;db=await new Promise((ok,no)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>stores.forEach(s=>{if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:'id'})});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return db}
export async function all(store){await initDB();return new Promise((ok,no)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
export async function put(store,value){await initDB();value.id=value.id||crypto.randomUUID();return new Promise((ok,no)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=()=>ok(value);r.onerror=()=>no(r.error)})}
export async function del(store,id){await initDB();return new Promise((ok,no)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=ok;r.onerror=()=>no(r.error)})}
export async function clear(store){await initDB();return new Promise((ok,no)=>{const r=db.transaction(store,'readwrite').objectStore(store).clear();r.onsuccess=ok;r.onerror=()=>no(r.error)})}
export const settings={get:(k,d)=>JSON.parse(localStorage.getItem('ado:'+k)??JSON.stringify(d)),set:(k,v)=>localStorage.setItem('ado:'+k,JSON.stringify(v))};
export async function exportData(){const data={version:1,exportedAt:new Date().toISOString(),settings:{accent:settings.get('accent','purple'),light:settings.get('light',false),aiEndpoint:settings.get('aiEndpoint','')},collections:{}};for(const s of stores)data.collections[s]=await all(s);return data}
export async function importData(data){if(!data?.collections)throw Error('Geçersiz yedek');for(const s of stores){await clear(s);for(const item of data.collections[s]||[])await put(s,item)}Object.entries(data.settings||{}).forEach(([k,v])=>settings.set(k,v))}
